### ISSUE TITLE
Undetermined error

### ISSUE THREAD

**Issue by CLMonteil** [Arkadiy-Garber/FeGenie#11]
Hello, I ran FeGenie successfully (thanks)
I was wondering the meaning of such error message (in bold) at the end on the job. May you tell

I ran the following command./FeGenie.py -bin_dir ./FeGenie_bins -bin_ext fasta -t 4 -out output_fegenie5
checking arguments
.
.
.
All required arguments provided!
Finding ORFs for MTL4.1-CDSs.fasta
starting main pipeline...
.
Looking for following iron-related functional category: iron_storage
analyzing MTL4.1-CDSs.fasta: 100%   
.
.........
.........
.
Looking for following iron-related functional category: magnetosome_formation
analyzing MTL4.1-CDSs.fasta: 100%   
**Consolidating summary files into one master summary file
Identifying genomic proximities and putative operons
Traceback (most recent call last):
  File "./FeGenie.py", line 2170, in <module>
    main()
  File "./FeGenie.py", line 843, in main
    CoordDict[i][contig].append(int(numOrf))
ValueError: invalid literal for int() with base 10: '130050|ID:75309160|bioA'**

**Comment by Arkadiy-Garber** [comment]
Hi,

Thanks for using FeGenie!

That error message indicates that something went wrong during the pipeline, and that is likely caused by the header names that are used in your provided FASTA file.

Are you providing FeGenie with genome contigs or gene sequences? From the file name "MTL4.1-CDSs.fasta" it sounds like you are providing gene sequences. If so, you would need to add the '--orfs' flag in the command.

Would you mind sending me the "MTL4.1-CDSs.fasta" file so that I can test it out on my system?

Thanks,
Arkadiy
