### ISSUE TITLE
FileNotFoundError on "Easy Installation (if you don't have Conda)"

### ISSUE THREAD

**Issue by diegusleik** [Arkadiy-Garber/FeGenie#12]
Hello, congratulations for your work.

I had an error while executing the last command on "Easy Installation (if you don't have Conda)" insctructions:

`./FeGenie.py -h`

, which throws to me:

`Traceback (most recent call last):
  File "./FeGenie.py", line 459, in main
    test = open(bits)
FileNotFoundError: [Errno 2] No such file or directory: '/HMM-bitcutoffs.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./FeGenie.py", line 2170, in <module>
    main()
  File "./FeGenie.py", line 467, in main
    location = allButTheLast(location, "/")
UnboundLocalError: local variable 'location' referenced before assignment`

With a little lookup, I replaced line #462 of FeGenie.py file from:

`os.system("which FeGenie.py > mainDir.txt")`

, to

`os.system("which ./FeGenie.py > mainDir.txt")`

, wich solved the problem for me. Just in case anyone has the same error.

**Comment by Arkadiy-Garber** [comment]
Hey, thanks for using FeGenie, and for bringing that error to my attention!

It looks like the error you are describing stems from the fact that the FeGenie.py script is not in your path. That is a requirement for the program to run if you don't go with the conda-based installation.

Glad you were able to fix it with that change though! Was the program able to run and successfully finish after you made that change? If not, I would suggest you put FeGenie in your $PATH in your .bash_profile, .profile, or .bashrc script, which is found in the home directory. Then, change line #462 back to the way it was, and try again. In case you are not familiar with setting paths in linux, you can check out this page: [](https://stackabuse.com/how-to-permanently-set-path-in-linux/)

Let me know if you have any other questions or issues!
Arkadiy

**Comment by Arkadiy-Garber** [comment]
Just realized that I forgot to enter the link to the page describing paths in linux: [](https://opensource.com/article/17/6/set-path-linux)
