### ISSUE TITLE
ValueError: could not convert string to float: 'EMPTY' in -bams option

### ISSUE THREAD

**Issue by gabriellerocap** [Arkadiy-Garber/FeGenie#19]
Running FeGenie using -bams options with 4 metagenomes, each with their own single bam file. FeGenie proceeds through the mapping of the first set of contigs then crashes. This happens on the first file no matter what (I have put them in different orders) and each individual metagenome and bam file work fine when run singly with the -bam option.
```
processing... P1DNA.contigs.fa
Output depth matrix to geomics_bam_test_out/P1DNA.contigs.fa.depth
jgi_summarize_bam_contig_depths 2.15 (Bioconda) 2020-07-03T11:59:07
Output matrix to geomics_bam_test_out/P1DNA.contigs.fa.depth
0: Opening bam: /Users/gabrielle/Desktop/GenomeFun/FeGenie/Testing/BamFiles/P1DNA.bam
Processing bam files
Thread 0 finished: P1DNA.bam with 3840282 reads and 2255380 readsWellMapped
Creating depth matrix file: geomics_bam_test_out/P1DNA.contigs.fa.depth
Closing most bam files
Closing last bam file
Finished
processing... P1DNA.contigs.fa
Traceback (most recent call last):
  File "/Users/gabrielle/Desktop/GenomeFun/FeGenie/FeGenie.py", line 2707, in <module>
    main()
  File "/Users/gabrielle/Desktop/GenomeFun/FeGenie/FeGenie.py", line 2341, in main
    Dict[cell][process].append(float(depthDict[cell][contig]))
ValueError: could not convert string to float: 'EMPTY'
```

Note--this was happening last week as well but I was worried it was perhaps because of how I had gotten the single -bam option to work by the metabat install, so I did not post then. Attaching my bam location file just in case.
[Bamlocations2.txt](https://github.com/Arkadiy-Garber/FeGenie/files/5030180/Bamlocations2.txt)

**Comment by Arkadiy-Garber** [comment]
Hi,

Thanks for letting me know about this issue. Based on this output, it looks like the error is caused by a discrepancy in header names between the summary output file and the file generated from the jgi_summarize_bam_contig_depths script. Could you please send me the first few rows of one of the output files created by the script (preferably the one made for "P1DNA.contigs.fa"), and a few sample header names for the corresponding FASTA file (e.g. P1DNA.contigs.fa). jgi_summarize_bam_contig_depths writes output files to a directly called "contigDepths" that should be in the main output directory.

I am also working on a FeGenie scrip with the --debug option, that will allow you to generate a file with more details about the error. I will upload this soon.

Thanks,
Arkadiy

**Comment by gabriellerocap** [comment]
Arkadiy--Thanks for your quick response--here are a variety of snips of my files. 
FYI--I have been running these by letting FeGenie call prodigal to find the orfs, since my contig names already had letters and underscores in them, the gene names I had previously derived from them also had this (and did not have the contig position at the end)  so did not work under the default expectations for FeGenie. I eventually plan to tack some text on the end of each of my previously called orfs with a different separator to be able to use the -orfs flag. Not sure if the contig names are contributing to this or not. Each contigs file works fine with its own single bam when using the -bam option. 
In the error it kind of looks like it finishes the first file, then starts trying to process it again instead of moving on to P4DNA_contigs.fa.....
Anyway, here you go, 
Gabrielle

Original contigs file `P1DNA.contigs.fa`
```
>P1DNA_15_kc3_L502
ATCGGGTAGCTATGCTTTAACGCAGGACACAGTTCTTGAGGATGTTAACCTAGTTATTGCTGGAGACTTAAACCTTAATGGATACACACTTACAGTACCTTGTGGTTCAGTAACAGTTAGTGGAAACTTTAATGGTGGTGGAACTCTTATCCATTGTGGAGCGCTTGTTGTGTCAGGAAATACACAAAACAATCCAACTATAACTCAAAACTGTAACTAATGAAAAGATTAGCAATAGTATTATTAGTATTAGGTTTCTTTAGTTGTTCAGAACAAGATAAAGGAATCGCTCAACCAAGTATTGAGTTTGGTGTGTATCAATGGGATTTAAACGAAAACTTGTTATATGTATTTGGCGAGTATAAGTTAAACATTATACAAGATGGTGTATTATCTTTTGATGGAGATTATCTCTTAGAAGACGGATTATTAACTATATGGGATGAAGTTGGATATAGTCTTACAAGACCTTTAGAATTAACTAGCAAAGGTTTCTTATTAG
>P1DNA_17_kc2_L525
ACGGTTACGACGAAACAAAAAGAGCGGGTATATTTAACGACGACGGAGAACAAACACACGGTAATGTTTGGTTTATTGATAATGGTCCTTATGTTGGTAGAAGAGAAAACTGTGTGTTAAGTGCGCGTTACACTCAACAGCTAGCGTACTGGGTCATAGGCCCTCTGTATAAGGGTGGGGTTGATGCTAGTGGTGGGCGTATAAATTTTGCTGTAAATGTTTTTCATGACGAAATAATGAACAATCACTTTGCACAACCCGCAGATGATAGTATTTCTAACTTTTTTGATATTGGTCGAGAAGGTGGTAACACGTACTACGACGAAGGTAATAATGTTGCACTAGTTAATCAAATAAATTCTGGTTTAAAATGGAGATTTAAAGAAGATCCGTCAGGGCAGGTTTATACTTTTTTACCTACTACAGCCATACATAAAAACCTTTTAAGATTTAGTAATAATAGAATACCTTTTCCACTTGCTAACCCTGGTTATCAAGGCGGTTCGCCTTTACCCTTAAGTTCCA
>P1DNA_23_kc5_L570
CGAGTTCTAAAATCGAGAGCGTCACCACGATAATGCGCTGATCTTTTCGCTGAGTGCTTGTATTTTTCTGTGCCTGATGTTATTACGCAAGGTTTGCCGAACTCGATATAGGCTGGTTCAATGATTGTGATTGCAGCTATAAGTACTTCAGCTCTACAACCATCTATGCTTGCACCTGATTTTACTATCATGCCAGCTTTACCACCACACCATTTTGGACATCAAACGTAAGATTGTATCTAACCAAGTGTCGGCATTGTTCGAGAAATGTTTTTGGCAATTCTGGCACAGCTCCCCCTGTTGTTTTGATTAGCTTTGGATTAGCTTGTGCTAGAAATTCATTAAGAAGGGCTTTAGGGTCTTCACCTTCTCTGCCATTTAAAGCAAGGTGTGAAACATATTCCCATTGAGTGATTATAGAGCTAGGCTGTGCTGCTTTGGCCTTCATCTTCACAAGACGATAAGCGTAATCTGTGCCGCCCGAATCAAGATTGAATGTATCCACACCTATTGCGCAAGGATAGCCATTAGAAACGAAATTAAAGTCATTACCGCCTGGGAGATTGCCTA
```
Here is the top of the FeGenie generated output orf_calls file `P1DNA.contigs.fa-proteins.faa`
```
>P1DNA_15_kc3_L502_1 # 2 # 220 # 1 # ID=1_1;partial=10;start_type=Edge;rbs_motif=None;rbs_spacer=None;gc_cont=0.393
SGSYALTQDTVLEDVNLVIAGDLNLNGYTLTVPCGSVTVSGNFNGGGTLIHCGALVVSGN
TQNNPTITQNCN*
>P1DNA_15_kc3_L502_2 # 220 # 501 # 1 # ID=1_2;partial=01;start_type=ATG;rbs_motif=None;rbs_spacer=None;gc_cont=0.298
MKRLAIVLLVLGFFSCSEQDKGIAQPSIEFGVYQWDLNENLLYVFGEYKLNIIQDGVLSF
DGDYLLEDGLLTIWDEVGYSLTRPLELTSKGFLL
>P1DNA_17_kc2_L525_1 # 3 # 524 # 1 # ID=2_1;partial=11;start_type=Edge;rbs_motif=None;rbs_spacer=None;gc_cont=0.385
GYDETKRAGIFNDDGEQTHGNVWFIDNGPYVGRRENCVLSARYTQQLAYWVIGPLYKGGV
DASGGRINFAVNVFHDEIMNNHFAQPADDSISNFFDIGREGGNTYYDEGNNVALVNQINS
GLKWRFKEDPSGQVYTFLPTTAIHKNLLRFSNNRIPFPLANPGYQGGSPLPLSS
>P1DNA_23_kc5_L570_1 # 3 # 191 # -1 # ID=3_1;partial=10;start_type=ATG;rbs_motif=GGxGG;rbs_spacer=5-10bp;gc_cont=0.418
MIVKSGASIDGCRAEVLIAAITIIEPAYIEFGKPCVITSGTEKYKHSAKRSAHYRGDALD
FRT
>

```
Here is the top of the `FeGenie-geneSummary.csv` file. (Unrelated(?), but this file always has double header rows for some reason, including runs where everything works)

```
category | genome/assembly | orf | HMM | bitscore | bitscore_cutoff | clusterID | heme_binding_motifs | protein_sequence
-- | -- | -- | -- | -- | -- | -- | -- | --
category | genome/assembly | orf | HMM | bitscore | bitscore_cutoff | clusterID | heme_binding_motifs | protein_sequence
iron_storage | P1DNA.contigs.fa | P1DNA_53742_kc3_L732_1 | PF00210-Ferritin_like_domain | 55.1 | 44 | 1 | 0 | MQGDKKIIALLNSALAVELIAINQYFLHARMYKNWGLEKLNKADYKISIEKMKHADALIERILF
iron_storage | P1DNA.contigs.fa | P1DNA_53742_kc3_L732_2 | PF00210-Ferritin_like_domain | 83.3 | 44 | 1 | 0 | MYEDFGLDKLCQQLDHEMQEEITHADALIKRILFLEGTPNLKSRRDLLIGKDVPSMLANDLILEMEVVAALKASITLCESEGDYQSREMLEKLLIDTEEDHVYWLEKQIGLIDKIGLQNYIQSYMGQHLPD*
iron_storage | P1DNA.contigs.fa | P1DNA_40017_kc9_L580_1 | PF00210-Ferritin_like_domain | 50.1 | 44 | 2 | 0 | MLADDLKTLLATSYAFVIKAQNFHWNVEGSDFSQYHQFFQGIYDEVYGNAIDQTAEYIRTLDVYAPGSFERFSELSVITGQIKIPRAMLMIKELQEDNEAIQLILKQTFESATAEKNEGIANFIAERMDAHAKHGWMLRSFLKESRE*
```



Here is the top of the `P1DNA.contigs.fa.depth` file 
```
contigName	contigLen	totalAvgDepth	P1DNA.bam	P1DNA.bam-var
P1DNA_15_kc3_L502	502	1.64205	1.64205	1.05099
P1DNA_17_kc2_L525	525	1.992	1.992	1.05074
P1DNA_23_kc5_L570	570	3.28333	3.28333	2.20832
P1DNA_26_kc32_L629	629	10.9749	10.9749	47.9282
P1DNA_28_kc6_L600	600	3.74	3.74	2.39327
P1DNA_30_kc4_L637	637	2.1191	2.1191	0.989905
```

**Comment by Arkadiy-Garber** [comment]
Hi Gabrielle,

Thanks for posting these file snips! That's very helpful.

It looks like all your files are formatted well, and should not be the cause of any problems in FeGenie. I just went through the FeGenie script and removed a small bug that was possibly causing this issue. I uploaded an updated version of the software to the FeGenie GitHub repository. When you get a chance, could you please download the updated version and try the -bams option again.

Thanks!
Arkadiy

**Comment by gabriellerocap** [comment]
Hi Arkadiy, Sorry for the delay. I have done a complete reinstall of FeGenie via Conda but I still get the same error when using the -bams option. 
Gabrielle
