### ISSUE TITLE
Error when cluster ORFs

### ISSUE THREAD

**Issue by Rachael-16** [Arkadiy-Garber/FeGenie#20]
Hi there, 

I've run into a new problem with running FeGenie. Previously I've run the script with no issue however now I receive the following error everytime I try to run

`Consolidating summary files into one master summary file
Identifying genomic proximities and putative operons
Clustering ORFs...
Looking for Thermincola S-layer cytochromes and Geobacter-related porin-cytochrome operons
Pre-processing of final outout file
rm: cannot remove 'fegenie_out4/GeoThermin.csv': Text file busy
rm: cannot remove 'fegenie_out4/magnetosome_formation-summary.csv': Text file busy
rm: cannot remove 'fegenie_out4/FinalSummary-dereplicated-clustered-blast.csv': Text file busy
rm: cannot remove 'fegenie_out4/Afreen_L.plantarum202195_GCA_010586945.1_ASM1058694v1_genomic.fna-thermincola.blast': Text file busy
Counting heme-binding motifs
rm: cannot remove 'fegenie_out4/FeGenie-summary.csv': Text file busy
mv: cannot move 'fegenie_out4/FeGenie-summary-blasthits.csv' to 'fegenie_out4/FeGenie-summary.csv': Operation not permitted
Final processing of output
Traceback (most recent call last):
  File "/home/qiime/FeGenie/FeGenie.py", line 2719, in <module>
    main()
  File "/home/qiime/FeGenie/FeGenie.py", line 1596, in main
    if ls[6] != "cluster":
IndexError: list index out of range `

I see that updates were made to the FeGenie.py script 27 days ago I'm assuming this may be a an error do to the addition of some categories, however I'm not sure how to troubleshoot it. Any help you can offer would be appreciated.

Thanks

**Comment by Arkadiy-Garber** [comment]
Hi Rachael,

Thanks for using FeGenie. My suspicion is that this error is caused by the fact that the server running this program does not have time to propagate files to the NFS. So when FeGenie attempts to remove or re-name old files, it fails, eventually resulting in a crash because the right file names are not present in the output directory.

To try to resolve this, I added to the program instructions to wait 5 seconds every time a new file is written and closed. Hopefully, this should fix the issue. But if not, let me know, and I will look further into this.

Thanks,
Arkadiy
