### ISSUE TITLE
Error "hmmsearch: not found ... local variable 'hmmout' referenced before assignment" while running FeGenie

### ISSUE THREAD

**Issue by anapopov** [Arkadiy-Garber/FeGenie#29]
Hi, I'm interested in identifying iron related genes within a metatranscriptomics dataset. I have attempted providing a fasta with gene (nucleotide) or protein sequences as bellow, but I hit an error that says hmm not found. Please see below.

Thanks! Ana~

 

command: FeGenie.py -bin_dir ORFs/ -bin_ext fasta -out TEST_out --orfs
--------------------------------------------

All required arguments provided!

HMM
AsbE_petrobactin_synthesis-rep
Cyc1
Cyc2_repCluster1
.
.
.
GACE_1846
GACE_1847
nramp
zip
starting main pipeline...

2
Looking for following iron-related functional category: iron_storage
sh: 1: hmmsearch: not foundta: 33%   
rm: cannot remove 'TEST_out/test_proteins.fasta-HMM/Transferrin_TbpB_binding_protein_Haemophilus_influenzae_P44971.hmm.txt': No such file or directory
FeGenie cannot find the correct hmmsearch output files. If you provided gene or ORF-call sequences, please be sure to specify this in the command using the '--orfs' flag
Traceback (most recent call last):
  File "/home/.../FeGenie/FeGenie.py", line 3083, in <module>
    main()
  File "/home/.../FeGenie/FeGenie.py", line 821, in main
    for line in hmmout:
UnboundLocalError: local variable 'hmmout' referenced before assignment

**Comment by Arkadiy-Garber** [comment]
Hi Ana,

Thanks for your interest in FeGenie! Sorry that you are getting errors, but hopefully we can get to the bottom of what's causing this.

Could you tell me how you installed FeGenie?

Also, FeGenie does not accept nucleotide gene sequences. It will take protein sequences, but ideally, you should provide contigs if you can.

Thanks!
Arkadiy

**Comment by anapopov** [comment]
Thanks for your quick response Arkadiy!

I don't have conda, so I installed it within my vbox Ubuntu as per the alternative instructions:

git clone https://github.com/Arkadiy-Garber/FeGenie.git
cd FeGenie
bash setup.sh
./FeGenie.py -h

I added it to my path, and had to install r and prodigal also.

re: prodigal/contigs - I get the same error using the test run provided:

...
Looking for following iron-related functional category: iron_storage
sh: 1: hmmsearch: not foundctinomycetemcomitans.txt: 33%   
rm: cannot remove 'fegenie_out/Aggregatibacter_actinomycetemcomitans.txt-HMM/Transferrin_TbpB_binding_protein_Haemophilus_influenzae_P44971.hmm.txt': No such file or directory

**Comment by Arkadiy-Garber** [comment]
Hi Ana,

Based on what I can see from that error message, it looks like HMMER is not installed on your system (hmmsearch is the main command that FeGenie uses from the [HMMER package](http://hmmer.org/)). Here's a full list of dependencies that FeGenie requires: [https://github.com/Arkadiy-Garber/FeGenie/wiki/Installation](https://github.com/Arkadiy-Garber/FeGenie/wiki/Installation). However, I would highly recommend installing [Conda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/linux.html). It will make installation of FeGenie (and countless other programs) much easier. I can't count how many hours of needless installation Conda has saved me.

**Comment by anapopov** [comment]
Oops - I totally missed that. Likely because I previously had it installed. Thanks Arkadiy!

I'll try the contigs too. Very interested to see what we can dig up in this data.
Re: Conda - noted!

**Comment by Arkadiy-Garber** [comment]
Sounds good! Yes, I hope FeGenie helps you uncover some interesting iron genes! Let me know if you continue to have any issues.

Thanks,
Arkadiy
