### ISSUE TITLE
DIAMOND Verification:  local variable 'idxDict' referenced before assignment

### ISSUE THREAD

**Issue by mwittep** [Arkadiy-Garber/FeGenie#30]
After running FeGenie with a reference database (nr.dmnd) I get the error shown below. 
As an output I get the complete FeGenie-summary.csv and an empty file FeGenie-summary-altered.csv.

I think I can work with the complete summary file, but still wanted to report the bug. 

Command
`
FeGenie.py -bin_dir . -bin_ext fsa -out ../output_fegenie_seqs/ --meta -ref /share/references/library/nr -t 10
`

Error: 

```
Performing Diamond BLASTx search of putative iron genes against reference database
Counting heme-binding motifs
Final processing of output

Traceback (most recent call last):
  File "/XXX/XXX/miniconda3/envs/fegenie/bin/FeGenie.py", line 3020, in <module>
    main()
  File "/XXX/XXX/miniconda3/envs/fegenie/bin/FeGenie.py", line 2355, in main
    ls[0] + "," + ls[1] + "," + str(idxDict[ls[2]]) + "," + ls[3] + "," + ls[4] + "," + ls[
UnboundLocalError: local variable 'idxDict' referenced before assignment

```

**Comment by metalichen** [comment]
wanted to bump this issue up. Got the same problem.

Thanks for the tool!
Gulya

**Comment by Arkadiy-Garber** [comment]
Thanks, Gulya! I see that you are, like me, having a wild Friday evening! haha

I found and fixed the bug that was causing this issue, and pushed the latest changes to the FeGenie github repo. So if you download the latest version, it should work. Let me know if you have any other questions, or continue having issues.

Cheers,
Arkadiy

**Comment by metalichen** [comment]
Yep, that worked! Thanks a bunch!

oh yes, I'm all about friday fun. have a nice weekend, I hope it'll get nicer :)
