### ISSUE TITLE
Permission denied when moving files

### ISSUE THREAD

**Issue by aidanfoo96** [Arkadiy-Garber/FeGenie#36]
Hi Arkadiy, thanks very much for developing this great tool :) 

I'm trying to implement FeGenie, however, near the end of the analysis this error is raised:  

`Pre-processing of final outout file
Counting heme-binding motifs
mv: cannot move '../results/fegenie/FeGenie-summary-blasthits.csv/FeGenie-summary-blasthits.csv' to '../results/fegenie/FeGenie-summary-blasthits.csv/FeGenie-summary.csv': Permission denied
Final processing of output

Traceback (most recent call last):
  File "/home/fooa/miniconda3/envs/fegenie/bin/FeGenie.py", line 3020, in <module>
    main()
  File "/home/fooa/miniconda3/envs/fegenie/bin/FeGenie.py", line 1641, in main
    infile = open(outDirectory + "/FeGenie-summary.csv")
FileNotFoundError: [Errno 2] No such file or directory: '../results/fegenie/FeGenie-summary-blasthits.csv/FeGenie-summary.csv'`
 
I still get the cluster.csv file but the summary.csv file is empty. I have a feeling this might be due to the server I'm using at my uni, but wondering if this is a problem you've encountered before or might have a solution for? 

Thanks

Aidan

**Comment by Arkadiy-Garber** [comment]
Hi Aidan,

Thanks for your interest in FeGenie! This looks like an interesting error, which I've never encountered before.

It looks like a permissions thing, so if you try running on this a personal machine, then you might avoid running into this. In any case, could you please paste into chat the command that you used for this run.

Thanks!
Arkadiy

**Comment by DrRumble** [comment]
Hi! I am having nearly the exact same issue except I am on my personal laptop and not a cluster. I don't know what's wron g here exactly so any help would be appreciated!!!

**Comment by Arkadiy-Garber** [comment]
Thanks DrRumble, could you please share the command that you used for your FeGenie run?

**Comment by anestiskos** [comment]
Hi,

I am facing a similar issue. In the FeGenie-heatmap-data I can see that there are many missing values in cases that there were multiple hits according to the individual hmmer searches. The error messages that I get in the end is:

mv: cannot move '/Desktop/FeGenie/output/AC-MGN_MB.9.faa-HMM' to /Desktop/FeGenie/output/HMM_results/AC-MGN_MB.9.faa-HMM': Permission denied
Writen summary to file: /Desktop/FeGenie/output/FeGenie-geneSummary-clusters.csv for visual inspection
Writen summary to file: /Desktop/FeGenie/output/FeGenie-geneSummary.csv for downstream parsing and analyses
Writing heatmap-formatted output file: /Desktop/FeGenie/output/FeGenie-heatmap-data.csv

The command that I used is:
FeGenie.py -bin_dir /Desktop/FeGenie/FeGenietest/ -bin_ext faa -out /Desktop/FeGenie/output --orfs -t 4

**Comment by Arkadiy-Garber** [comment]
Hi, thanks for following up on this issue.

based on your command above, it looks like the issue is arising from the fact that you are instructing FeGenie to write files in the root directory of your system, where it might not have the correct permissions.

If I am interpreting your command correctly, because your output path `/Desktop/FeGenie/FeGenietest/` begins with a forward slash `/`, it is attempting to create files in the incorrect place. I believe the correct filepath should be instead: `~/Desktop/FeGenie/FeGenietest/ `and `~/Desktop/FeGenie/output`, that should correctly place the results in your **home** directory, not the **root**.

Let me know if that works!
Arkadiy

**Comment by anestiskos** [comment]
Hi Arkadiy,

I followed your recommendations. The analysis went through, but it still was not able to compile the final file with the stats. I tackled it by saving the temporary summary file and then used it to make the heatmap data. 

Thanks a lot,
Kostas
