### ISSUE TITLE
error depth = open("%s/%s.depth" % (outDirectory, cell)) | HELP PLS. 

### ISSUE THREAD

**Issue by DrRumble** [Arkadiy-Garber/FeGenie#40]
Hi Arkadiy, 

I am trying to run FeGenie with various bam file aligning to 2 different genomes. The command I am using is: 
FeGenie.py -bin_dir final_megahit_co_assemblies/ -bin_ext fa -out fegenie_total_A_C_output -t 10 -bams WL_fegenie_bam_map_test.tsv --meta --makeplots

Except with the absolute paths, the thing is I keep getting the following as a output, 
I have removed and reinstalled FeGenie and reconfigured my environment and etc but I can't figure out whats wrong.

here is the error output

...

Looking for Thermincola S-layer cytochromes and Geobacter-related porin-cytochrome operons
Pre-processing of final outout file
Counting heme-binding motifs
Final processing of output

Writen summary to file: fegenie_total_A_C_output/FeGenie-geneSummary-clusters.csv for visual inspection
Writen summary to file: fegenie_total_A_C_output/FeGenie-geneSummary.csv for downstream parsing and analyses
Writing heatmap-formatted output file: fegenie_total_A_C_output/FeGenie-heatmap-data.csv

processing... final_megahit_co_assemblies/WL_A_metaG_co_assemblies.fa
Output depth matrix to fegenie_total_A_C_output/final_megahit_co_assemblies/WL_A_metaG_co_assemblies.fa.depth
jgi_summarize_bam_contig_depths 2.15 (Bioconda) 2020-07-03T11:59:07
Output matrix to fegenie_total_A_C_output/final_megahit_co_assemblies/WL_A_metaG_co_assemblies.fa.depth
0: Opening bam: /Users/oliviaannerumble/bioinformatics/Waterlogging_project/Metatranscriptomic_WL_files/metaT_DRY_A/RQCF_DRY_A_files/Dry_A_bam_files/sorted_bam_files/WD-19_S10_L001_A_paired_mapped_sorted.bam
0: Opening bam: /Users/oliviaannerumble/bioinformatics/Waterlogging_project/Metatranscriptomic_WL_files/metaT_DRY_A/RQCF_DRY_A_files/Dry_A_bam_files/sorted_bam_files/WD-19_S10_L002_A_paired_mapped_sorted.bam
Processing bam files
WARNING: your aligner reports an incorrect NM field.  You should run samtools calmd! nm < ins + del: cmatch=0 nm=33 ( insert=0 + del=44 + mismatch=33 == 77) D00472:89:HLFHMBCXX:1:1103:11614:22137 1:N:0:GAGATTCC+TAATCTTA
Thread 0 finished: WD-19_S10_L001_A_paired_mapped_sorted.bam with 1140574 reads and 117839 readsWellMapped
Thread 0 finished: WD-19_S10_L002_A_paired_mapped_sorted.bam with 1168778 reads and 120993 readsWellMapped
Creating depth matrix file: fegenie_total_A_C_output/final_megahit_co_assemblies/WL_A_metaG_co_assemblies.fa.depth
Closing most bam files
Closing last bam file
Finished
processing... final_megahit_co_assemblies/WL_A_metaG_co_assemblies.fa
Traceback (most recent call last):
  File "/Users/oliviaannerumble/miniconda3/envs/fegenie/bin/FeGenie.py", line 2636, in main
    depth = open("%s/contigDepths/%s.depth" % (args.out, cell))
FileNotFoundError: [Errno 2] No such file or directory: 'fegenie_total_A_C_output/contigDepths/final_megahit_co_assemblies/WL_A_metaG_co_assemblies.fa.depth'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/oliviaannerumble/miniconda3/envs/fegenie/bin/FeGenie.py", line 3139, in <module>
    main()
  File "/Users/oliviaannerumble/miniconda3/envs/fegenie/bin/FeGenie.py", line 2652, in main
    depth = open("%s/%s.depth" % (outDirectory, cell))
FileNotFoundError: [Errno 2] No such file or directory: 'fegenie_total_A_C_output/final_megahit_co_assemblies/WL_A_metaG_co_assemblies.fa.depth'

**Comment by Arkadiy-Garber** [comment]
Hi! Sorry for letting this issue fall through the cracks. If you are still on this, could you please re-install with the latest version, and let me know if you still see this error.

Thanks,
Arkadiy
