### ISSUE TITLE
'Namespace' object has no attribute 'hbm'

### ISSUE THREAD

**Issue by Sxxnwei** [Arkadiy-Garber/FeGenie#44]
Hi Arkadiy,

I am trying to use FeGenie to identify proteins involved in iron reduction. 

My inputs are two amino acid fasta files from two metatranscritptome data. they are significant genes estimated by edgeR.   
I ran the command:
(fegenie) sxxn@Seans-MacBook-Pro ~ % FeGenie.py -bin_dir /Volumes/SEAN/edgeR_DEG/ --orfs --skip -bin_ext fasta -out fegenie_out  

then i got this:
Ok, proceeding with analysis!
All required arguments provided!

Traceback (most recent call last):
  File "/Users/sxxn/miniconda3/envs/fegenie/bin/FeGenie.py", line 3020, in <module>
    main()
  File "/Users/sxxn/miniconda3/envs/fegenie/bin/FeGenie.py", line 2744, in main
    if args.hbm:
       ^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'hbm'

and here is my input fasta:
>4085_2
MRLTTKGRFAVTAMIDVALRQHAGPVTLAGIAERQKISLSYLEQLFGKLRRNQLVASTRGPGGGYTLAKPLAAVSVADIISAVDEPLDATSCGGRGNCHDDHPCMTHDLWMSLNARMHEYLSSVNLDHLVRQQGIKGCANEAQPVTIGKAPARRIPVMATA*
>7_1
MKVTKIFTHGLLWVIIVMLVIPPGIMAQDTEETVQSAQFNEEELAQMLAPIALYPDSLIAEILMASTYPIEVVEAER
>9_1
MKGMKIYIKGLSWVIIVMLMMPPGLMAQDSGQIEQPVKFNKEELAQMLAPIALYPDSLIAQILMASTYPIEVVEAERWIRKNKNLTGDELDSALQEKTWDPSVKSLCHFPDILYAMSEKLDQTTKLGDAFLSQQDEVMDTIQELRRKAQEQGNLTTTKEQKVIVEQETIYIEPANPEIIYVPAYDPLYVYGPWWYPAYP

Any idea I can fix this error?

Thanks,
Sean

**Comment by Arkadiy-Garber** [comment]
Hi Sean,

Thanks for your interest in FeGenie! I am having trouble reconciling the error with the current version of FeGenie that's currently on GitHub. When did you install this software? In any case, could you please try re-installing it and trying to run the program again. Looking at the error message, it looks like an older version of the software.

Thanks!
Arkadiy
