### ISSUE TITLE
running programm with reference database for blast searches throws error

### ISSUE THREAD

**Issue by ckeuschn** [Arkadiy-Garber/FeGenie#46]
Hi, 

When I run the program providing a reference database it throws an error which I cannot figure out how to solve. Any help is appreciated! 

Cheers, 
Christoph 

/Final processing of output

Traceback (most recent call last):
  File "/home/ckeuschn/miniconda3/envs/fegenie/bin/FeGenie.py", line 3020, in <module>
    main()
  File "/home/ckeuschn/miniconda3/envs/fegenie/bin/FeGenie.py", line 2355, in main
    ls[0] + "," + ls[1] + "," + str(idxDict[ls[2]]) + "," + ls[3] + "," + ls[4] + "," + ls[
                                    ^^^^^^^
UnboundLocalError: cannot access local variable 'idxDict' where it is not associated with a value
/

**Comment by Arkadiy-Garber** [comment]
Hi Christoph,

Thanks for your interest in FeGenie, and apologies for the delayed response.

Thanks for sharing that error output. Could you please send me the command that you are using to invoke FeGenie?

Thanks,
Arkadiy

**Comment by ckeuschn** [comment]
Hi Arkadiy, 

sorry I missed your response here an I am back now on this again. I have still problems with running the programm with a refDB. this is my command: 

FeGenie.py \
       -bin_dir .\
       -bin_ext faa \
       -out fegenie_out_uniprot \
       --orfs \
       -t 16\
       -ref /home/ckeuschn/databases/uniprot_sprot.fasta

but that gives me an empty output file now:

head FeGenie-summary.csv
category,genome,assembly,orf,HMM,bitscore,bitscore_cutoff,cluster,heme_binding_motifs,top_blast_hit,blast_hit_evalue,protein_sequence
#,#,#,#,#,#,#,#
#,#,#,#,#,#,#,#
#,#,#,#,#,#,#,#
#,#,#,#,#,#,#,#
#,#,#,#,#,#,#,#

When I run it without a database I get a table with hits and everything. what am I missing here?  
Thanks a lot!
