### ISSUE TITLE
IndexError during Final processing of output

### ISSUE THREAD

**Issue by zreitz** [Arkadiy-Garber/FeGenie#9]
Running the quick-start fasta files directly following a conda install gives the following error:

```
FeGenie.py -bin_dir test_pao1/ -bin_ext txt -t 1
checking arguments
.
.
.
All required arguments provided!

Finding ORFs for Pseudomonas_aeruginosa_PA01.txt
starting main pipeline...

.
Looking for following iron-related functional category: iron_aquisition-heme_oxygenase
analyzing Pseudomonas_aeruginosa_PA01.txt: 100%   

.
Looking for following iron-related functional category: iron_aquisition-heme_transport
analyzing Pseudomonas_aeruginosa_PA01.txt: 100%   

.
Looking for following iron-related functional category: iron_aquisition-iron_transport
analyzing Pseudomonas_aeruginosa_PA01.txt: 100%   

.
Looking for following iron-related functional category: iron_aquisition-siderophore_synthesis
analyzing Pseudomonas_aeruginosa_PA01.txt: 100%   

.
Looking for following iron-related functional category: iron_aquisition-siderophore_transport
analyzing Pseudomonas_aeruginosa_PA01.txt: 100%   

.
Looking for following iron-related functional category: iron_gene_regulation
analyzing Pseudomonas_aeruginosa_PA01.txt: 100%   

.
Looking for following iron-related functional category: iron_oxidation
analyzing Pseudomonas_aeruginosa_PA01.txt: 100%   

.
Looking for following iron-related functional category: iron_reduction
analyzing Pseudomonas_aeruginosa_PA01.txt: 100%   

.
Looking for following iron-related functional category: iron_storage
analyzing Pseudomonas_aeruginosa_PA01.txt: 100%   

.
Looking for following iron-related functional category: magnetosome_formation
analyzing Pseudomonas_aeruginosa_PA01.txt: 100%   


Consolidating summary files into one master summary file
Identifying genomic proximities and putative operons
Clustering ORFs...

.
Looking for Thermincola S-layer cytochromes and Geobacter-related porin-cytochrome operons
Pre-processing of final outout file
Counting heme-binding motifs
Final processing of output

Traceback (most recent call last):
  File "/home/snip/FeGenie/FeGenie.py", line 2167, in <module>
    main()
  File "/home/snip/FeGenie/FeGenie.py", line 1414, in main
    memoryDict[dataset][orf]["seq"] = ls[10]
IndexError: list index out of range
```

Platform: Debian 10
Python 3.7.6

**Comment by Arkadiy-Garber** [comment]
Hi,

Thanks for using FeGenie, and for bringing my attention to this issue!
This error stemmed from a small bug in the script that was just fixed. Apologies for the inconvenience.

Feel free to re-run the program after a new `git clone https://github.com/Arkadiy-Garber/FeGenie.git`

Thanks,
Arkadiy

**Comment by zreitz** [comment]
Thank you! That fixed the issue.
